version: '3.8'
services:
  cockroach:
    image: cockroachdb/cockroach:v24.2.1
    container_name: cockroach
    command: start-single-node --insecure
    volumes:
      - /project/data/cockroachdb:/cockroach/cockroach-data
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI

