version: '3.9'

services:
  # Master PostgreSQL Node
  pg_master:
    image: postgres:latest
    container_name: pg_master
    restart: always
    networks:
      - dc_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: server_db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /project/data/pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose master

networks:
  dc_network:

